<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Promise学习</title>
  
</head>
<body>

</body>
<script type="text/javascript">
//用Promise的时候一般是包在一个函数中，在需要的时候去运行这个函数
/*Promise的构造函数接收一个参数，是函数，并且传入两个参数：

resolve，reject的用法
分别表示异步操作执行成功后的回调函数和异步操作执行失败后的回调函数。其实这里用“成功”和“失败”来描述并不准确，按照标准来讲，resolve是将Promise的状态置为fullfiled，reject是将Promise的状态置为rejected。*/

//实例一 
	function run(){
		var p = new Promise(function(resolve, reject){
			setTimeout(function(){
            	var num = Math.ceil(Math.random()*10); //生成1-10的随机数
            	if(num<=5){
            	    resolve(num);
            	}
            	else{
            	    reject('数字太大了');
            	}
        	}, 2000);
		});
		return p;
	}

	run().then(function(data){
		console.log(data);
	},function(reason, data){
		console.log(data);
	})


//实例二：有多层回调
	function runAsync1(){
    var p = new Promise(function(resolve, reject){
        //做一些异步操作
        setTimeout(function(){
            console.log('异步任务1执行完成');
            resolve('随便什么数据1');
        }, 1000);
    });
    return p;            
}
function runAsync2(){
    var p = new Promise(function(resolve, reject){
        //做一些异步操作
        setTimeout(function(){
            console.log('异步任务2执行完成');
            resolve('随便什么数据2');
        }, 2000);
    });
    return p;            
}
function runAsync3(){
    var p = new Promise(function(resolve, reject){
        //做一些异步操作
        setTimeout(function(){
            console.log('异步任务3执行完成');
            resolve('随便什么数据3');
        }, 2000);
    });
    return p;            
}

runAsync1()
.then(function(data){
    console.log(data);
    return runAsync2();//return 一个promise对象
})
.then(function(data){
    console.log(data);
    return runAsync3();
})
.then(function(data){
    console.log(data);
});



/*实例三：catch用法
效果和写在then的第二个参数里面一样。不过它还有另外一个作用：在执行resolve的回调（也就是上面then中的第一个参数）时，如果抛出异常了（代码出错了），那么并不会报错卡死js，而是会进到这个catch方法中。


*/
run()
.then(function(data){
    console.log('resolved');
    console.log(data);
})
.catch(function(reason){
    console.log('rejected');
    console.log(reason);
});



run()
.then(function(data){
    console.log('resolved');
    console.log(data);
    console.log(somedata); 
    //此处的somedata未定义在resolve的回调中而somedata这个变量是没有被定义的。如果不用Promise，代码运行到这里就直接在控制台报错了，不往下运行了。进到catch方法里面去了，而且把错误原因传到了reason参数中。即便是有错误的代码也不会报错了，这与我们的try/catch语句有相同的功能。
})
.catch(function(reason){
    console.log('rejected');
    console.log(reason);
});

/*实例四：all的用法

Promise的all方法提供了并行执行异步操作的能力，并且在所有异步操作执行完后才执行回调。仍旧使用上面定义好的runAsync1、runAsync2、runAsync3这三个函数；

应用场景：
有一个场景是很适合用这个的，一些游戏类的素材比较多的应用，打开网页时，预先加载需要用到的各种资源如图片、flash以及各种静态文件。所有的都加载完后，再进行页面的初始化

*/
Promise
.all([runAsync1(), runAsync2(), runAsync3()])
.then(function(results){
    console.log(results);
});

/*
实例五：race的用法
all方法的效果实际上是「谁跑的慢，以谁为准执行回调」，那么相对的就有另一个方法「谁跑的快，以谁为准执行回调」，这就是race方法，这个词本来就是赛跑的意思。race的用法与all一样，我们把上面runAsync1的延时改为1秒来看一下：
复制代码*/
Promise
.race([runAsync1(), runAsync2(), runAsync3()])
.then(function(results){//返回数据在以数组的形式保存results中
    console.log(results);
});
	
</script>
</html>